export const LOADING_PROGRESS = 'LOADING_PROGRESS'

export const GET_LATEST_ENTRIES = 'GET_LATEST_ENTRIES'
export const GET_LATEST_ENTRIES_SUCCESS = 'GET_LATEST_ENTRIES_SUCCESS'

export const GET_ENTRY = 'GET_ENTRY'
export const GET_ENTRY_SUCCESS = 'GET_ENTRY_SUCCESS'

export const GET_ABOUTME = 'GET_ABOUTME'
export const GET_ABOUTME_SUCCESS = 'GET_ABOUTME_SUCCESS'

export const API_ERROR = 'API_ERROR'
export const ERROR_RESET = 'ERROR_RESET'