'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var LOADING_PROGRESS = exports.LOADING_PROGRESS = 'LOADING_PROGRESS';

var GET_LATEST_ENTRIES = exports.GET_LATEST_ENTRIES = 'GET_LATEST_ENTRIES';
var GET_LATEST_ENTRIES_SUCCESS = exports.GET_LATEST_ENTRIES_SUCCESS = 'GET_LATEST_ENTRIES_SUCCESS';

var GET_ENTRY = exports.GET_ENTRY = 'GET_ENTRY';
var GET_ENTRY_SUCCESS = exports.GET_ENTRY_SUCCESS = 'GET_ENTRY_SUCCESS';

var GET_ABOUTME = exports.GET_ABOUTME = 'GET_ABOUTME';
var GET_ABOUTME_SUCCESS = exports.GET_ABOUTME_SUCCESS = 'GET_ABOUTME_SUCCESS';

var API_ERROR = exports.API_ERROR = 'API_ERROR';
var ERROR_RESET = exports.ERROR_RESET = 'ERROR_RESET';